version: '3'
services:
  flask_app:
    build: .
    container_name: flask_app_container  # Set the container name
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    environment:
      FLASK_ENV: development
    command: flask run --host=0.0.0.0
